### ISSUE TITLE
consider support for modern web languages

### ISSUE THREAD

**Issue by musketyr** [kdabir/glide#2]
it would be nice if I can use CoffeeScript and LESS with Glide. As you are already copying/syncing files from one folder to another it might be quite simple to also process some files with compiler.

https://code.google.com/p/wro4j/ might be good fit for this or you can just use less4j etc.

**Comment by kdabir** [comment]
Now that glide has become a gradle plugin, the modern js-based tech stacks can be easily integrated the same way for any other java web app.
Even better, a public folder can be configured inside `app` as public-root so that it can be served by appengine's static web-server.
