### ISSUE TITLE
glide.groovy servlets config generation

### ISSUE THREAD

**Issue by matjazonline** [kdabir/glide#38]
I would like to generate web.xml servlet definitions from glide.groovy : 
```
web {
    servlets {
        templateTest1Servlet {
            servletClass = "grooplateServlet"
            initParams = ['verbose' : false, 'generated.by' : false ]
            urlPatterns = ['OK.gtpl']
        }
    }
}
```

this generates following web.xml servlet definition:

```
<servlet>
    <servlet-name>templateTest1Servlet</servlet-name>
    <servlet-class />
    <load-on-startup />
</servlet>
```
and no servlet mapping.

**Comment by kdabir** [comment]
What version of glide are you using (i.e. version of glide-gralde plugin)? are you running via glide command line or via gradle task (either way can you provide command that you executed)? I will try to provide a fix or workaround.


locally, I am trying with the following plugin config and it works as expected.
```
plugins {
  id "com.appspot.glide-gae" version "0.9.4"
}
```

```
  <servlet>
    <servlet-name>templateTest1Servlet</servlet-name>
    <servlet-class>grooplateServlet</servlet-class>
    <init-param>
      <param-name>verbose</param-name>
      <param-value>false</param-value>
    </init-param>
    <init-param>
      <param-name>generated.by</param-name>
      <param-value>false</param-value>
    </init-param>
    <load-on-startup />
  </servlet>
...
  <servlet-mapping>
    <servlet-name>templateTest1Servlet</servlet-name>
    <url-pattern>OK.gtpl</url-pattern>
  </servlet-mapping>
```

**Comment by matjazonline** [comment]
Hi Kunal,
I 'm using 0.9.3 with "glide appRun" - I'll try with 0.9.4 and now I've seen it's "gradle appRun".

Thank you for replying,
have a great day,
Matjaz

**Comment by matjazonline** [comment]
solved, Kunal thanks for help!

**Comment by kdabir** [comment]
Cool. Glad to help.
